name: albausalah_app
description: albausalah

publish_to: 'none'
version: 1.2.2

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  get: ^4.6.5
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  loading_animation_widget: ^1.2.0+4
  flutter_animated_icons: ^1.0.1
  flutter_rating_bar: ^4.0.1
  animated_bottom_navigation_bar: ^1.1.0+1
  favorite_button: ^0.0.4
  flutter_add_to_cart_button: ^1.1.0
  get_storage: ^2.1.1
  webview_flutter: ^3.0.4
  url_launcher: ^6.1.10
  image_picker: ^0.8.7+4
  font_awesome_flutter: ^10.4.0
  shimmer: ^2.0.0
  intl_phone_number_input: ^0.7.1
  permission_handler: 10.2.0
  buttons_tabbar: ^1.3.6
  flutter_svg: 2.0.5
  animated_icon_button: ^1.0.2
  cool_dropdown: ^1.4.2
#  flutter_facebook_auth : ^5.0.7
  firebase_auth: ^4.2.8
  google_sign_in: ^5.4.4
  loading_icon_button: ^0.0.5+1
  video_player: ^2.6.1
  file_picker: 5.2.11
  dashed_circle: ^0.0.2
  geolocator: ^9.0.2
  flutter_udid: ^2.0.1
  collection: ^1.17.0
  flutter_instagram_storyboard: ^0.0.8
  easy_autocomplete: ^1.6.0
  flutter_cache_manager: ^3.3.0
  rxdart: ^0.27.7
  syncfusion_flutter_sliders: ^21.2.9
  emoji_keyboard_flutter: ^1.3.1
  visibility_detector: ^0.4.0+2
  input_history_text_field: ^0.2.0
  persistent_bottom_nav_bar: ^5.0.2
  curved_navigation_bar: ^1.0.3
  floating_bottom_bar: ^0.0.2
  gradient_borders: ^1.0.0
  animated_splash_screen: ^1.3.0
  flutter_osm_plugin: ^0.53.4+1
  onesignal_flutter: ^3.5.1
  pointer_interceptor: ^0.9.3+4
  geocoding: ^2.1.0
  provider: ^6.0.5
  chatview: ^1.2.0+1
  emoji_picker_flutter: ^1.6.0
  audio_waveforms: ^1.0.4
  grouped_list: ^5.1.2
  any_link_preview: ^3.0.0
  chat_bubbles: ^1.4.1
  sizer: ^2.0.15
  audioplayers: ^4.1.0
  just_audio: ^0.9.34
  video_thumbnail: ^0.5.3
  share_plus: ^7.0.2
  file_selector: ^1.0.0
  device_info_plus: ^9.0.3











dev_dependencies:
  
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/albausalah.png"


flutter:


  uses-material-design: true
  assets:
    - assets/icons/add.png
    - assets/icons/add_1.png
    - assets/icons/add_follow.png
    - assets/icons/add_job.png
    - assets/icons/albausalah.png
    - assets/icons/avatar.png
    - assets/icons/bag.png
    - assets/icons/best_seller.png
    - assets/icons/booking.png
    - assets/icons/box.png
    - assets/icons/chat.png
    - assets/icons/delivery.png
    - assets/icons/followers.png
    - assets/icons/following.png
    - assets/icons/free_delivery.png
    - assets/icons/gift.png
    - assets/icons/info.png
    - assets/icons/job.png
    - assets/icons/no_products.png
    - assets/icons/not_found.png
    - assets/icons/notification.png
    - assets/icons/offer.png
    - assets/icons/order.png
    - assets/icons/package.png
    - assets/icons/power-off.png
    - assets/icons/precision.png
    - assets/icons/profile.png
    - assets/icons/report.png
    - assets/icons/return.png
    - assets/icons/shopping-bag.png
    - assets/icons/slider1.svg
    - assets/icons/slider2.svg
    - assets/icons/store.png
    - assets/icons/store_1.png
    - assets/icons/store_2.png
    - assets/icons/story.png
    - assets/icons/user_1.png
    - assets/icons/vehicle.png
    - assets/icons/view.png
    - assets/photos/albausalah_logo.png
    - assets/photos/home_newsletter.png
    - assets/photos/place_holder.png
    - assets/photos/record.png
    - assets/photos/slider.png
    - assets/test/adidas_logo.png
    - assets/test/fila_logo.png
    - assets/test/mask.png
    - assets/test/nike_logo.png
    - assets/test/puma_logo.png
    - assets/test/vans_logo.png
    - shorebird.yaml
